create database BANK;
USE BANK;
CREATE TABLE EMPLOYEE
(EMP_ID VARCHAR(25),
EMP_NAME VARCHAR(25),
EMP_DOMAIN VARCHAR(25),
EMP_SALARY INTEGER(255));
INSERT INTO EMPLOYEE(EMP_ID,EMP_NAME,EMP_DOMAIN,EMP_SALARY) VALUES
("01","AJAY","ANALYST",5000),
("02","VIJAY","DATA",8000),
("03","JAY","TESTING",9000),
("04","SUJAL","MANAGER",50000);
select * FROM EMPLOYEE;
