CREATE DATABASE SHOP;
USE SHOP;
CREATE TABLE ITEMS
(COUT_ID INT PRIMARY KEY,
COUT_NAME VARCHAR(25),
COUT_AGE INT(255),
cOUT_SHOP VARCHAR(25));
INSERT INTO ITEMS(COUT_ID,COUT_NAME,COUT_AGE,cOUT_SHOP) VALUES
(01,"AJAY",22,"ELECTRONICS"),
(02,"VIJAY",24,"GAME"),
(03,"JAY",20,"BOOKS"),
(04,"SURAYA",25,"GROCERY");
SELECT * FROM ITEMS;
DESC ITEMS;
UPDATE ITEMS SET COUT_AGE=28 WHERE COUT_ID=2;
UPDATE ITEMS SET COUT_NAME="SUJAL" WHERE COUT_ID=1;
DELETE FROM ITEMS WHERE COUT_ID=3;
